#!/bin/sh

set -eu

lb config noauto \
    --mode debian \
    --distribution sid \
    --architectures amd64 \
    --archive-areas "main contrib non-free-firmware" \
    --security false \
    --updates false \
    --backports false \
    --cache false \
    --binary-images iso-hybrid \
    --bootloaders "syslinux,grub-efi" \
    --debian-installer none \
    --image-name fanne-linux \
    --iso-application "Fanne Linux Unstable" \
    --iso-publisher "Tervia Interactive" \
    --iso-volume "FANNE_UNSTABLE" \
    --bootappend-live "boot=live components username=fanne user-fullname=Fanne hostname=fanne locales=en_US.UTF-8 keyboard-layouts=us timezone=UTC" \
    "${@}"
